leftnav:
- identifier: b512b90e-ddf3-d123-4acc-0d9f5e4a7ff9
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 81674f09-eae1-8d69-98ca-5cd68ec98e95
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 8e97ad61-5a17-09fa-6ecd-9633ab2ab9d9
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: c6e346b5-4e40-7683-cec6-2e232671cc3c
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 29b25fcc-09a9-90a5-f208-00656d126d01
  name: Tools
  pageRef: /pages/tools
  weight: 50
